title: "Marco Dell'Oro"
author: "Marco Dell'Oro"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layoute
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "assets/marcoCV.pdf", title: "CV"}
  - {file: "Project.md", title: "Projects"}  # Assuming you have a projects page
  - {file: "AboutMe.md", title: "About Me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:marcodelloro99@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Marcodelloro"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/marco-d-590a36140/"}
  - {title: X, icon: x-twitter, url: "https://x.com/mvrcodelloro"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
