title: "Marco Dell'Oro"
author: "Marco Dell'Oro"
description: "<span style='font-size: 11px;'>&#169; Marco Dell'Oro, <i>latest update June 2025</i></span>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

sass:
  sass_dir: _sass
  style: compressed

# Layout
show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

navigation:     
  - {title: "CV", url: "/cv/"}
  - {title: "Projects", url: "/projects/"}  # Assuming you have a projects page
  - {title: "More", file: "More.md"}

external:
  - {title: Mail, icon: envelope, url: "mailto:marcodelloro99@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Marcodelloro"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/marco-d-590a36140/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
